name: pyodi
channels:
  - anaconda
dependencies:
  - python=3.6
  - cython
  - numpy
  - matplotlib
  - pandas
  - pip:
    - fire
    - loguru
    - plotly
    - streamlit
    - git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
