name: pyodi
channels:
  - anaconda
dependencies:
  - python=3.6
  - cython
  - numpy
  - matplotlib
  - pandas
  - flake8
  - pytest
  - pip:
    - typer
    - loguru
    - plotly
    - pre-commit
    - git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
