site_name: Object Detection Insights
site_url: "http://pyodi.org"

theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo.svg
nav:
  - Home: index.md
  - Reference:
      - apps:
          - ground-truth: reference/apps/ground-truth.md
plugins:
  - search
  - mkdocstrings:
      watch:
        - pyodi
