name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda environment
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        activate-environment: pyodi
        environment-file: conda.yaml
    - name: Install pyodi
      shell: bash -l {0}
      run: |
        which pip
        which python
        pip install .
    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Typecheck with mypy
      shell: bash -l {0}
      run: |
        mypy -p pyodi
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest
